export type Genres = {
    Action: boolean,
    Adventure: boolean,
    Arcade: boolean,
    ['Brain training']: boolean,
    Casual: boolean,
    ['Driving/Racing']: boolean,
    Educational: boolean,
    Family: boolean,
    Fighting: boolean,
    Fitness: boolean,
    Horror: boolean,
    ['Music/Rhythm']: boolean,
    Party: boolean,
    Puzzle: boolean,
    Quiz: boolean,
    ['Role playing games']: boolean,
    Shooter: boolean,
    Simulation: boolean,
    Simulator: boolean,
    Sport: boolean,
    Strategy: boolean,
    Unique: boolean,
    [key: string]: boolean;
};